name: iOS CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove CI DerivedData
        run: rm -rf ./DerivedData

      - name: Generate project
        run: make

      - name: Resolve Swift Packages
        run: |
          xcodebuild \
          -resolvePackageDependencies \
          -scheme Unify-Test \
          -derivedDataPath ./DerivedData

      - name: Build
        run: |
          xcodebuild \
          -scheme Unify-Test \
          -derivedDataPath ./DerivedData \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          clean build
